### ISSUE TITLE
`nix upgrade-nix` should be removed or hidden in this version of Nix

### ISSUE THREAD

**Issue by therealpxc** [dezgeg/nix-fpm-multiuser#4]
An attempt results in an error message as follows:

```
root@LightningBug:~# nix upgrade-nix
error: directory '/opt/nix-multiuser/nix/bin' does not appear to be part of a Nix profile
```

Since this is intentional, maybe the `upgrade-nix` command should be removed for this build.

**Comment by dezgeg** [comment]
It has this sort of code for NixOS:

````
        if (hasPrefix(where, "/run/current-system"))
            throw Error("Nix on NixOS must be upgraded via 'nixos-rebuild'");
````

So yeah, something similar should be done.

**Comment by dezgeg** [comment]
Fixed, I switched to a nix fork with a similar change added. So `git submodule sync` is probably needed on rebuild.
