### ISSUE TITLE
Default profile not added to PATH for users

### ISSUE THREAD

**Issue by therealpxc** [dezgeg/nix-fpm-multiuser#5]
When I saw that [`nix upgrade-nix` does not work](https://github.com/dezgeg/nix-fpm-multiuser/issues/4), I decided to try giving users on my Ubuntu 18.04 (Bionic) system access to the latest Nix by installing it on the default profile. However, this did not achieve the expected results because the default profile is not added to the `PATH`s of users.

```
root@LightningBug:~# nix-env -qP
0  nix-2.0.2
root@LightningBug:~# nix --version
nix (Nix) 2.0.2
root@LightningBug:~# /opt/nix-multiuser/nix/bin/nix --version
nix (Nix) 2.0pre6125_3ec1b3d
root@LightningBug:~# echo $PATH
/root/.nix-profile/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/opt/nix-multiuser/nix/bin
root@LightningBug:~# exit
logout
pxc@LightningBug:~$ nix --version
nix (Nix) 2.0pre6125_3ec1b3d
pxc@LightningBug:~$ echo $PATH
/home/pxc/.nix-profile/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/nix-multiuser/nix/bin
pxc@LightningBug:~$
```

Is this intended behavior? It's a significant divergence from NixOS and the way that Nix profiles work on macOS and non-NixOS Linux (when installed manually).

Edit: It makes sense to me for the default profile to be empty, as described in the readme, but the default profile being off the PATH means that Nix can't be used (without some changes to /etc/profile or whatever) to install global packages at all. Is that what is desired here?

**Comment by dezgeg** [comment]
Yeah, seems like a bug. I use the same `scripts/nix-profile.sh` as the single-user install which does set `NIX_PROFILES="@localstatedir@/nix/profiles/default $NIX_USER_PROFILE_DIR"` but then only adds `~/.nix-profile/bin` to PATH.

**Comment by dezgeg** [comment]
I fixed this in my local fork, to be upstreamed later.
